name: ReplaySystem
version: '${project.version}'
main: de.bukkitnews.replay.ReplaySystem
author: BukkitNews
api-version: 1.21
depend:
  - packetevents
commands:
  replay:
    description: Replay Command